SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(avg(B.REVIEW_SCORE), 2) SCORE
FROM REST_INFO a INNER JOIN REST_REVIEW b on a.REST_ID = b.REST_ID
WHERE substr(ADDRESS, 1, 2) = "서울"
GROUP BY 1, 2
ORDER BY SCORE desc, FAVORITES desc