Select ROUTE,
       CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1),'km') as TOTAL_DISTANCE,
       CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2),'km') as AVERAGE_DISTANCE
from SUBWAY_DISTANCE
Group by ROUTE
Order by ROUND(SUM(D_BETWEEN_DIST), 2) desc