WITH RECURSIVE TIME AS(
SELECT 0 AS HOUR
UNION ALL
SELECT HOUR+1 FROM TIME WHERE HOUR < 23)
SELECT HOUR, COUNT(hour(DATETIME)) COUNT
FROM TIME a LEFT JOIN ANIMAL_OUTS b ON a.HOUR = hour(b.DATETIME)
GROUP BY a.HOUR