WITH RECURSIVE CTE AS(
SELECT 0 HOUR
UNION ALL
SELECT HOUR+1 FROM CTE WHERE HOUR < 23)
SELECT a.HOUR, COUNT(hour(b.DATETIME)) COUNT
FROM CTE a LEFT JOIN ANIMAL_OUTS b ON a.HOUR = hour(b.DATETIME)
GROUP BY a.HOUR