SELECT MEMBER_ID, MEMBER_NAME, GENDER, Date_format(DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE Date_format(DATE_OF_BIRTH, '%m') = 03 and TLNO IS NOT null and GENDER = "W"
ORDER BY MEMBER_ID