WITH CTE AS (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT a.SCORE, a.EMP_NO, b.EMP_NAME, b.POSITION, b.EMAIL
FROM CTE a LEFT JOIN HR_EMPLOYEES b ON a.EMP_NO = b.EMP_NO
WHERE SCORE = (SELECT MAX(SCORE) FROM CTE)