SELECT CASE WHEN (CATEGORY LIKE '%Front End%') AND (SKILL LIKE '%Python%') THEN 'A'
            WHEN (SKILL LIKE '%C#%') THEN 'B'
            WHEN (CATEGORY LIKE '%Front End%') THEN 'C' END GRADE,
       ID, EMAIL
FROM
(
SELECT a.ID, a.EMAIL, GROUP_CONCAT(b.NAME) SKILL, GROUP_CONCAT(DISTINCT b.CATEGORY) CATEGORY
FROM DEVELOPERS a LEFT JOIN SKILLCODES b ON (a.SKILL_CODE & b.CODE) = b.CODE
GROUP BY a.ID, a.EMAIL
) c
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID